### ISSUE TITLE
cfg_atoi exec error on linux

### ISSUE THREAD

**Issue by ly1243667342** [morrowind/libconfig#1]
first，thanks ！
cfg_atoi exec error on linux ,after"value *= (int)strtol(strings->array[i], &endptr, 0);", endptr is not NULL。

**Comment by morrowind** [comment]
> first，thanks ！
> cfg_atoi exec error on linux ,after"value *= (int)strtol(strings->array[i], &endptr, 0);", endptr is not NULL。

Hi, thanks for your remind, it's fixed now.
