### ISSUE TITLE
cfg_atoi bug

### ISSUE THREAD

**Issue by xiao-gengen-round** [morrowind/libconfig#3]
in your code, in function cfg_atoi, 

                    **if(isEmpty(trim(strings->array[i])))**

i think need to change as follow:

            **if(isEmpty(strings->array[i] = trim(strings->array[i])))**

because strings->array is char** type

**Comment by morrowind** [comment]
> in your code, in function cfg_atoi,
> 
> ```
>                 **if(isEmpty(trim(strings->array[i])))**
> ```
> 
> i think need to change as follow:
> 
> ```
>         **if(isEmpty(strings->array[i] = trim(strings->array[i])))**
> ```
> 
> because strings->array is char** type

Yes，Thank your for your remind, I have fixed it.
